config/routes.rb
Rails.application.routes.draw do
  resources :jobs, only: [:index, :show, :new, :create] do
  end
  # get 'jobs', to: 'jobs#index'
  # get 'jobs/new', to: 'jobs#new'
  # post 'jobs', to: 'jobs#create'
  # get 'jobs/:id', to: 'jobs#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show]

  def index
    @jobs = Job.all
  end

  def show
    @job
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :school, :salary, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="container">
  <h1>Job vacancies</h1>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Job Title</th>
      <th scope="col">School</th>
      <th scope="col">Salary</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.title, job_path(job.id) %></td>
        <td><%= job.school %></td>
        <td><%= "£ #{job.salary} p/a"%></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <h1>Create a new job vacancy</h1>
  <%= form_for(@job) do |f| %>
    <div class="form-group">
      <%= f.label :job_title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :school %>
      <%= f.text_field :school, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.label :salary %>
      <%= f.text_field :salary, class: 'form-control' %>
    </div>

     <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <%= f.submit "save", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="card" style="width: 24rem;">
     <div class="card-header">
      <h2><%= @job.title %></h2>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @job.school %></h5>
      <h5 class="card-title"><%= "#{@job.salary}" %></h5>
      <p class="card-text"><%= @job.description %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vacancies dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>